apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: app
          image: nexus:latest
          ports:
            - containerPort: 8000
