# SPDX-License-Identifier: MPL-2.0
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libffi-dev

      - name: Bootstrap toolchain
        run: make bootstrap

      - name: Run quality gate
        run: make check

      - name: Generate SBOM
        run: ./scripts/sbom

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage.xml
            htmlcov/
          if-no-files-found: ignore

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom/
          if-no-files-found: ignore

  license-compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run ScanCode Toolkit
        uses: nexB/scancode-toolkit-action@v32.2.0
        with:
          args: --copyright --license --summary --failcode 1 -n 4 .

      - name: Verify SPDX headers with REUSE
        uses: fsfe/reuse-action@v2
